### PR TITLE
test_files: Remove non *.hdl files

### PR DESCRIPTION
**Pull request by vacuus**

### CODE REVIEW

**Comment by zbrachinara** [comment]
I think it's better to leave these in, since eventually we will have to test this too. The end goal is to have apps which have all the features of the official ones, which includes development of hack hdl using test scripts.

**Comment by vacuus** [comment]
Makes sense. In that case, should the non *.hdl files for the other projects be added to the repository as well?

**Comment by vacuus** [comment]
Though the *.out files don't need to be kept in, right?

**Comment by zbrachinara** [comment]
I think they're part of how the *.tst files work, as in that's what the output of the chip is checked against when there's an `output` statement in a test file

**Pull request closed without merging**
